env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:cypress/recommended'
  - airbnb
  - prettier
  - 'plugin:@next/next/recommended'
plugins:
  - react
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'
rules:
  import/extensions:
    - error
    - always
    - js: never
      jsx: never
      ts: never
      tsx: never
  no-unused-vars: 'off'
  react/function-component-definition:
    - 2
    - namedComponents: arrow-function
  react/jsx-indent:
    - 0
  react/react-in-jsx-scope: 0
  react/jsx-indent-props:
    - 2
    - 4
  react/jsx-props-no-spreading: 'off'
  react/jsx-filename-extension:
    - 1
    - extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
  no-use-before-define:
    - 0
  react/display-name: 0
  react/prop-types: 0
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/explicit-member-accessibility': 0
  '@typescript-eslint/indent': 0
  '@typescript-eslint/member-delimiter-style': 0
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-use-before-define': 0
  '@typescript-eslint/no-unused-vars':
    - 1
    - argsIgnorePattern: '^_'
  no-console: 1
  no-plusplus: 0
  import/prefer-default-export: 1
  no-shadow: 1
  prefer-const: 1
  prefer-spread: 1
  no-unused-expressions:
    - error
    - allowShortCircuit: true
      allowTernary: true
  no-return-assign: 'off'
  no-underscore-dangle: 'off'
  react/require-default-props:
    - 2
    - ignoreFunctionalComponents: true
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - state
  import/no-extraneous-dependencies:
    - 2
    - devDependencies:
          - 'scripts/*.mjs'
          - 'scripts/*.js'
          - 'scripts/*.ts'
          - '**/*.test.js'
          - '**/*.test.ts'
          - '**/*.spec.js'
          - '**/*.spec.ts'
settings:
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
      moduleDirectory:
        - node_modules
        - src/
