name: Build NextJS App and Deploy to Netlify Standard Environments

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Client
      run: npm ci

    - name: Test Client
      run: npm test -- --passWithNoTests

    - name: Build Client
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      run: npm run build

  deploy_to_dev:
    name: Deploy To Dev
    environment: 
      name: dev
      url: 'https://dev--azanay-tech-sas.netlify.app'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Client
        run: npm ci

      - name: 🚀 Deploy to Netlify Dev
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DEPLOYMENT_ALIAS: dev
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_ENVIRONMENT: dev
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          NEXT_PUBLIC_SENTRY: ${{ secrets.ENABLE_SENTRY }}
          NEXT_PUBLIC_LOGROCKET: ${{ secrets.ENABLE_LOGROCKET }}
          NEXT_PUBLIC_LOGROCKET_ID: ${{ secrets.LOGROOCKET_ID }}
          NEXT_PUBLIC_APP_USER_ID: ${{ secrets.APP_USER_ID }}
          NEXT_PUBLIC_SUBSCRIPTION_TYPE: ${{ secrets.SUBSCRIPTION_TYPE }}
          NEXT_PUBLIC_CLIENT_ID: ${{ secrets.LOG_ROCKET_CLIENT_ID }}
        run: |
          npx netlify-cli deploy --build --site "$NETLIFY_SITE_ID" --auth "$NETLIFY_AUTH_TOKEN" --open --alias "$DEPLOYMENT_ALIAS"

      - name: Cypress E2E on Dev
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          headless: true
          config: baseUrl=https://dev--azanay-tech-sas.netlify.app
          tag: dev
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  promote_to_stage:
    name: Approval to Promote to Stage
    environment: 
      name: internal:promote_to_stage
    runs-on: ubuntu-latest
    needs: deploy_to_dev
    steps:
      - name: Promotion approved
        run: echo "Promotion to stage approved"

  deploy_to_stage:
    name: Deploy to Stage
    environment: 
      name: stage
      url: 'https://stage--azanay-tech-sas.netlify.app'
    runs-on: ubuntu-latest
    needs: promote_to_stage
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Client
        run: npm ci

      - name: 🚀 Deploy to Netlify Stage
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DEPLOYMENT_ALIAS: stage
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_ENVIRONMENT: stage
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          NEXT_PUBLIC_SENTRY: ${{ secrets.ENABLE_SENTRY }}
          NEXT_PUBLIC_LOGROCKET: ${{ secrets.ENABLE_LOGROCKET }}
          NEXT_PUBLIC_LOGROCKET_ID: ${{ secrets.LOGROOCKET_ID }}
          NEXT_PUBLIC_APP_USER_ID: ${{ secrets.APP_USER_ID }}
          NEXT_PUBLIC_SUBSCRIPTION_TYPE: ${{ secrets.SUBSCRIPTION_TYPE }}
          NEXT_PUBLIC_CLIENT_ID: ${{ secrets.LOG_ROCKET_CLIENT_ID }}
        run: |
          npx netlify-cli deploy --build --site "$NETLIFY_SITE_ID" --auth "$NETLIFY_AUTH_TOKEN" --open --alias "$DEPLOYMENT_ALIAS"

      - name: Cypress E2E on Stage
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          headless: true
          config: baseUrl=https://stage--azanay-tech-sas.netlify.app
          tag: stage
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  promote_to_prod:
    name: Approval to Promote to Production
    environment: 
      name: internal:promote_to_prod
    runs-on: ubuntu-latest
    needs: deploy_to_stage
    steps:
      - name: Promotion approved
        run: echo "Promotion to production approved"

  deploy_to_prod:
    name: Deploy to Production
    environment:
      name: production
      url: 'https://azanay-tech-sas.netlify.app'
    runs-on: ubuntu-latest
    needs: promote_to_prod
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Client
        run: npm ci

      - name: 🚀 Deploy to Netlify Production
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_ENVIRONMENT: production
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          NEXT_PUBLIC_SENTRY: ${{ secrets.ENABLE_SENTRY }}
          NEXT_PUBLIC_LOGROCKET: ${{ secrets.ENABLE_LOGROCKET }}
          NEXT_PUBLIC_LOGROCKET_ID: ${{ secrets.LOGROOCKET_ID }}
          NEXT_PUBLIC_APP_USER_ID: ${{ secrets.APP_USER_ID }}
          NEXT_PUBLIC_SUBSCRIPTION_TYPE: ${{ secrets.SUBSCRIPTION_TYPE }}
          NEXT_PUBLIC_CLIENT_ID: ${{ secrets.LOG_ROCKET_CLIENT_ID }}
        run: |
          npx netlify-cli deploy --build --site "$NETLIFY_SITE_ID" --auth "$NETLIFY_AUTH_TOKEN" --open --prod