name: Build NextJS App and Deploy to Netlify Preview Environment

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Client
      run: npm ci

    - name: Test Client
      run: npm test -- --passWithNoTests

    - name: Code Format - ESLint
      run: npm run lint:check

    - name: Code Format - Prettier
      run: npm run prettier:check

    - name: Build Client
      run: npm run build

    - name: 🚀 Deploy to Netlify Preview Env
      id: netlify_preview_deployment
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        echo "::set-output name=deployed_url::$(npx netlify-cli deploy --build --site "$NETLIFY_SITE_ID" --auth "$NETLIFY_AUTH_TOKEN" --open | grep -oP '(?<=Website Draft URL: ).*' | xargs)"
