name: Build React App and Deploy to Netlify Preview Environment

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test and Build Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Client
      run: npm ci

    - name: Test Client
      run: npm test -- --passWithNoTests

    - name: Code Format - ESLint
      run: npm run lint:check

    - name: Code Format - Prettier
      run: npm run prettier:check

    - name: Build Client
      run: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build
        path: .next
        retention-days: 1