name: Build NextJS App and Deploy to Netlify Preview Environment

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Client
      run: npm ci

    - name: Test Client
      run: npm test -- --passWithNoTests

    - name: Code Format - ESLint
      run: npm run lint:check

    - name: Code Format - Prettier
      run: npm run prettier:check

    - name: Build Client
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      run: npm run build

    - name: 🚀 Deploy to Netlify Preview Env
      id: netlify_preview_deployment
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        NEXT_PUBLIC_ENVIRONMENT: preview-${{ github.head_ref }}
        NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        NEXT_PUBLIC_SENTRY: ${{ secrets.ENABLE_SENTRY }}
        NEXT_PUBLIC_LOGROCKET: ${{ secrets.ENABLE_LOGROCKET }}
        NEXT_PUBLIC_LOGROCKET_ID: ${{ secrets.LOGROOCKET_ID }}
        NEXT_PUBLIC_APP_USER_ID: 'azanay-tech-preview'
        NEXT_PUBLIC_SUBSCRIPTION_TYPE: ${{ secrets.SUBSCRIPTION_TYPE }}
        NEXT_PUBLIC_CLIENT_ID: 'preview-client'
      run: |
        echo "::set-output name=deployed_url::$(npx netlify-cli deploy --build --site "$NETLIFY_SITE_ID" --auth "$NETLIFY_AUTH_TOKEN" --open | grep -oP '(?<=Website Draft URL: ).*' | xargs)"

    - name: Find existing deployment comment on PR
      uses: peter-evans/find-comment@v1
      id: find_comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: Netlify Preview Deployment

    - name: Create PR comment with deployment URL
      if: steps.find_comment.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v1
      env:
        DEPLOYED_URL: ${{ steps.netlify_preview_deployment.outputs.deployed_url }}
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          🚀 Netlify Preview Deployment:
          ${{ steps.netlify_preview_deployment.outputs.deployed_url }}

    - name: Update existing comment with deployment URL
      if: steps.find_comment.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v1
      env:
        DEPLOYED_URL: ${{ steps.netlify_preview_deployment.outputs.deployed_url }}
      with:
        comment-id: ${{ steps.find_comment.outputs.comment-id }}
        body: |
          🚀 Netlify Preview Deployment:
          ${{ steps.netlify_preview_deployment.outputs.deployed_url }}
        edit-mode: replace